### PR TITLE
utils/expect: new package

### PR DESCRIPTION
**Pull request by rwasef1830**
Signed-off-by: Raif Atef <beliskner.github.3psil0N@neverbox.com>

Compile tested: ARMv7 Kernel 2.6 Softfloat
Run tested: Netgear R7000 Freshtomato ARM 2020.1

### CODE REVIEW

**Comment by rwasef1830** [comment]
The included patches are sourced from buildroot project: 
https://github.com/buildroot/buildroot/tree/master/package/expect

**Comment by The-BB** [comment]
https://github.com/Entware/Entware/issues/364

**Comment by rwasef1830** [comment]
Hello,
I apologise for duplicate.
That issue is closed. So I thought it was abandoned. This one is compile
and also run tested. I don't have mipsel or aarch64 to test. But I am happy
to test if you make an arm kernel 2.6 version.

**Comment by ryzhovau** [comment]
@rwasef1830, thanks for cooperation! TCL was broken for uclibc-ng based distros, so we [forced to downgrade](https://github.com/Entware/entware-packages/blob/master/lang/tcl/Makefile#L7) it and remove multithead support. 

We've got our own Makefile from those times proven as useless for a reason described above. As long as we switched to full-blown glibc, we promise to return to this question and add `expect` after few tests. I'll cherry-pick this commit to rtndev feed than.

Thanks again! And take a look at PR guideline next time:) This is a wrong feed to add new packages.

**Pull request closed without merging**
