### PR TITLE
gost_engine: changed /usr to /opt, added patch for CMakeLists OPENSSL…

### PR DESCRIPTION
**Pull request by ghost**
Changed /usr to /opt, added patch for CMakeLists.txt OPENSSL_INCLUDE_DIR.

### CODE REVIEW

**Comment by ghost** [comment]
Additionally tested, it works

**Comment by ryzhovau** [comment]
Thanks for PR!
Unfortunately, we see no reason to enable openssl engines for now, so we'll keep this PR open.
Please, tell us about your GOST cyphers use case.

**Comment by ghost** [comment]
> Thanks for PR!
> Unfortunately, we see no reason to enable openssl engines for now, so we'll keep this PR open.
> Please, tell us about your GOST cyphers use case.

Hello!
I agree with you, I left it just in case. This one is not that important. If the firmware is built with the engine, then no changes are required. It is recommended to build such things into the firmware.

As You can see  
https://github.com/openwrt/openwrt/commit/12a80e44b914a00fa39daae5474b3964f246ddc3  
openssl always build with GOST engine.

**Comment by ryzhovau** [comment]
Closing for now.

**Pull request closed without merging**
